name: CovidCare Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    
    - name: Git Pull
      run: git pull
      working-directory: C:/Users/Administrator/actions-runner/knotters/covidcare/covidcare
      
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
